# When the todo list on the user's dashboard becomes empty, a random message
# from the list below will be shown.
#
# If you come up with a fun one, please feel free to contribute it to GitLab!
# https://about.gitlab.com/contributing/
--- 
- 干的好！你没有未完成的todo。
- 没有doto的列表是不是很美丽？
- 从今往后你被称为"Todo终结者"。
